- name: Install bash dependencies
  hosts: all

  vars:
    packages:
      - curl
      - bash
      - python3
      - unzip

  tasks:
    - name: Install packages
      package:
        name: "{{ packages }}"
        state: present
